kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: leo
data:
  default.conf: |
    server {
      listen 80;
      #server_name leo.k8s.com;
      location / {
        proxy_pass http://wordpress-svc.leo:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
      #  try_files $uri $uri/ /index.php?$args;
        }
    }
