apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: leo
  labels:
     app: wordpress
spec:
#  type: ClusterIP
#  loadBalancerSourceRanges:
#    - "116.241.212.54/32"
#  externalTrafficPolicy: Local
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
