apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: leo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: check-db-ready
        image: imega/mysql-client
        command:
          - 'sh'
          - '-c'
          - 'until mysqladmin ping -h mysql-svc &> /dev/null; do echo waiting; sleep 2; done'
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-svc:3306
          - name: WORDPRESS_DB_USER
            value: leo
          - name: WORDPRESS_DB_PASSWORD
            value: royal1688
          - name: WORDPRESS_DB_NAME
            value: wordpress
        ports:
        - containerPort: 80
          name: wp-port
        resources:
         requests:
            cpu: 50m
            memory: 100Mi
         limits:
            cpu: 100m
            memory: 256Mi
        startupProbe:
          tcpSocket:
            port: wp-port
          initialDelaySeconds: 5
          failureThreshold: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: wp-port
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: wp-port
          periodSeconds: 3
          timeoutSeconds: 3
#        envFrom:
#          - configMapRef:
#              name: env
        volumeMounts:
          - name: data-volume
            mountPath: /var/www/html
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
