apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: leo
  labels:
     app: wordpress
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 80
#  - port: 443
#    name: https
#    protocol: TCP
#    targetPort: 443
  selector:
    app: wordpress
