apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: leo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: IfNotPresent
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-svc:3306
          - name: WORDPRESS_DB_USER
            value: leo
          - name: WORDPRESS_DB_PASSWORD
            value: royal1688
          - name: WORDPRESS_DB_NAME
            value: wordpress        
        ports:
        - containerPort: 80
#          name: wp-port
#        resources:
#         requests:
#            cpu: 50m
#            memory: 100Mi
#         limits:
#            cpu: 100m
#            memory: 256Mi
#        envFrom:
#          - configMapRef:
#              name: env
#        startupProbe:
#          tcpSocket:
#            port: wp-port
#          initialDelaySeconds: 30
#          failureThreshold: 60
#          timeoutSeconds: 3
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: wp-port
#          failureThreshold: 3
#          periodSeconds: 10
#          timeoutSeconds: 3
#        readinessProbe:
#          tcpSocket:
#            port: wp-port
#          periodSeconds: 3
#          timeoutSeconds: 3
        volumeMounts:
          - name: data-volume
            mountPath: /var/www/html      
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume