apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
     app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 3000
    nodePort: 30500
  selector:
    app: grafana
