apiVersion: v1
kind: Pod
metadata:
  name: nginx-leo
  namespace: leo
  labels:
    service: nginx
spec:
  containers:
   - name: web
     image: nginx:latest
     ports:
     - containerPort: 80
     #env:
     #- name: TZ
     #  value: Asia/Taipei
