apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: leo
  labels:
     app: test
spec:
  containers:
   - name: nginx-test
     image: nginx
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 80
