apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-mc002002
  namespace: rcg
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector: 
    matchLabels:
      service: gcs-mc002002
  template:
    metadata:
      labels:
        service: gcs-mc002002
    spec:
      imagePullSecrets:
        - name: gcrsecret
      containers:
        - name: gcs-mc002002
          image: gcr.io/modern-renderer-315105/m2-gcs-dev:DEV20220608-03
          imagePullPolicy: Always       
          env:
          - name: "StevenCode"
            value: mc002002
          envFrom:
            - configMapRef:
                name: environment
          ports:
           - containerPort: 3000
             name: web-socket
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi



