apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-wm001001
  namespace: rcg
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector: 
    matchLabels:
      service: gcs-wm001001
  template:
    metadata:
      labels:
        service: gcs-wm001001
    spec:
      imagePullSecrets:
        - name: gcrsecret
      containers:
        - name: gcs-wm001001
          image: gcr.io/modern-renderer-315105/m2-gcs-dev:DEV20220601-01
          imagePullPolicy: Always       
          env:
          - name: "GCS_Guid"
            value: 8B360EF1-3454-4087-87D3-44CF56A64490
          - name: "ServerId"
            value: gcs-wm001001            
          envFrom:
            - configMapRef:
                name: environment
          ports:
           - containerPort: 3000
             name: web-socket
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi



