apiVersion: v1
kind: Service
metadata:
  name: tmp-svc
  namespace: rcg
  labels:
     service: tmp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: tmp-id
