apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: lens-metrics
  labels:
    app: alertmanager
spec:
  #type: ClusterIP
  ports:
  - port: 9093
    name: web
    targetPort: 9093
  selector:
    app: alertmanager