apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: wordpress
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
