apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
  labels:
     app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: web
    protocol: TCP
    nodePort: 30080
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
