apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: leo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: nginx-port
        resources:
         requests:
            cpu: 50m
            memory: 100Mi
         limits:
            cpu: 100m
            memory: 256Mi
        startupProbe:
          tcpSocket:
            port: nginx-port
          initialDelaySeconds: 5
          failureThreshold: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: nginx-port
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: nginx-port
          periodSeconds: 3
          timeoutSeconds: 3
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            readOnly: true
            name: nginx-config
            subPath: nginx.conf
          - mountPath: /etc/nginx/conf.d/wordpress.conf
            readOnly: true
            name: nginx-config
            subPath: wordpress.conf    
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
#          items:
#          - key: nginx.conf
#            path: nginx.conf
#          - key: wordpress.conf
#            path: conf.d/wordpress.conf