apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: leo
  labels:
     app: nginx
spec:
  type: NodePort
  ports:
  - port: 3000
    name: web
    protocol: TCP
    targetPort: 3000
    nodePort: 30080
#  - port: 443
#    name: https
#    protocol: TCP
#    targetPort: 443
  selector:
    app: nginx
