apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: leo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: nginx-port
        resources:
         requests:
            cpu: 50m
            memory: 100Mi
         limits:
            cpu: 100m
            memory: 256Mi
#        volumeMounts:
#          - mountPath: /etc/nginx
#            readOnly: true
#            name: nginx-config
#      volumes:
#      - name: nginx-config
#        configMap:
#          name: nginx-config
#          items:
#          - key: nginx.conf
#            path: nginx.conf
#          - key: wordpress.conf
#            path: conf.d/wordpress.conf