apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-gc004001
  namespace: rcg
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector: 
    matchLabels:
      service: gs-gc004001
  template:
    metadata:
      labels:
        service: gs-gc004001
    spec:
      imagePullSecrets:
        - name: gcrsecret
      containers:
        - name: gs-gc004001
          image: gcr.io/modern-renderer-315105/m2-gs-dev:DEV20220609-01
          imagePullPolicy: IfNotPresent                    
          env:
          - name: "GS_Guid"
            value: 95284F0A-4FAF-4C55-85DE-A0173CA26C01
          - name: "ServerId"
            value: gs-gc004001
          - name: "DeskCode"
            value: gc004001
          envFrom:
            - configMapRef:
                name: environment
          ports:
           - containerPort: 80
             name: web-socket
          resources:
            limits:
              cpu: 700m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
              - name: redis-settings # Redis è¨­å?æª?
                readOnly: true
                mountPath: /app/appsettings.REDIS.json
                subPath: appsettings.REDIS.json
              - name: loglevel-settings # Redis è¨­å?æª?
                readOnly: true
                mountPath: /app/appsettings.LOGLEVEL.json
                subPath: appsettings.LOGLEVEL.json
      volumes:
        - name: loglevel-settings
          configMap:
            name: loglevel-settings
        - name: redis-settings
          configMap:
            name: redis-settings




